using System.Collections.Generic;
using Wholesome_Auto_Quester.Helpers;
using wManager.Wow.Helpers;

namespace Wholesome_Auto_Quester.Database.DBC
{
    class DBCFaction
    {
        private static List<Reputation> _myReputations = new List<Reputation>();
        private static object _repLock = new object();

        public static Reputation GetReputationById(int repId)
        {
            lock (_repLock)
            {
                return _myReputations.Find(rep => rep.Id == repId); // can be null
            }
        }

        public static void RecordReputations()
        {
            string luaReps = Lua.LuaDoString<string>($@"
                local result  = """";
                for i=1, 40 do 
                    local name, description, standingID, _, _, barValue, _, _, isHeader, _, _, _, _ = GetFactionInfo(i);
                    if (not isHeader) and name ~= nil then
                        result = result .. '$' .. name .. '|' .. standingID .. '|' .. barValue
                    end
                end
                return result
            ");
            string[] reps = luaReps.Split('$');
            lock (_repLock)
            {
                _myReputations.Clear();
                foreach (string rep in reps)
                {
                    string[] repProperties = rep.Split('|');
                    if (repProperties.Length < 3)
                    {
                        continue;
                    }
                    _myReputations.Add(new Reputation(repProperties[0], repProperties[1], repProperties[2]));
                }
            }
        }
    }
}

public class Reputation
{
    public int Id { get; }
    public string Name { get; }
    public int Amount { get; }
    FactionStanding StandingId { get; }

    private Dictionary<FactionStanding, int> _reputationMasks = new Dictionary<FactionStanding, int>()
    {
        {  FactionStanding.Hated, 1 },
        {  FactionStanding.Hostile, 2 },
        {  FactionStanding.Unfriendly, 4 },
        {  FactionStanding.Neutral, 8 },
        {  FactionStanding.Friendly, 16 },
        {  FactionStanding.Honored, 32 },
        {  FactionStanding.Revered, 64 },
        {  FactionStanding.Exalted, 128 }
    };

    public int GetFactionMask => _reputationMasks[StandingId];

    public Reputation(string name, string standingId, string amount)
    {
        Name = name;

        if (int.TryParse(standingId, out int id))
        {
            StandingId = (FactionStanding)id;
        }
        else
        {
            throw new System.Exception($"Couldn't parse {name} reputation standing Id");
        }

        if (int.TryParse(amount, out int am))
        {
            Amount = am;
        }
        else
        {
            throw new System.Exception($"Couldn't parse {name} reputation amount");
        }

        string trimmedName = name.Trim();
        if (reputationIds.TryGetValue(trimmedName, out int repId))
        {
            Id = repId;
        }
        else
        {
            // Use a default ID for unknown reputations instead of crashing
            Logger.Log($"Couldn't find {name} in reputation ID dictionary, using default ID 0");
            Id = 0;
        }
    }

    private Dictionary<string, int> reputationIds = new Dictionary<string, int>()
    {
        { "PLAYER, Human", 1 },
        { "人类(玩家)", 1 },
        { "PLAYER, Orc", 2 },
        { "兽人(玩家)", 2 },
        { "PLAYER, Dwarf", 3 },
        { "矮人(玩家)", 3 },
        { "PLAYER, Night Elf", 4 },
        { "暗夜精灵(玩家)", 4 },
        { "PLAYER, Undead", 5 },
        { "亡灵(玩家)", 5 },
        { "PLAYER, Tauren", 6 },
        { "牛头人(玩家)", 6 },
        { "Creature", 7 },
        { "生物", 7 },
        { "PLAYER, Gnome", 8 },
        { "侏儒(玩家)", 8 },
        { "PLAYER, Troll", 9 },
        { "巨魔(玩家)", 9 },
        { "Monster", 14 },
        { "怪物", 14 },
        { "Defias Brotherhood", 15 },
        { "迪菲亚盗贼", 15 },
        { "Gnoll - Riverpaw", 16 },
        { "河爪豺狼人", 16 },
        { "Gnoll - Redridge", 17 },
        { "赤脊山豺狼人", 17 },
        { "Gnoll - Shadowhide", 18 },
        { "暗皮豺狼人", 18 },
        { "Murloc", 19 },
        { "鱼人", 19 },
        { "Undead, Scourge", 20 },
        { "亡灵(天灾军团)", 20 },
        { "Booty Bay", 21 },
        { "藏宝海湾", 21 },
        { "Beast - Spider", 22 },
        { "蜘蛛", 22 },
        { "Beast - Boar", 23 },
        { "野猪", 23 },
        { "Worgen", 24 },
        { "狼人", 24 },
        { "Kobold", 25 },
        { "狗头人", 25 },
        { "Troll, Bloodscalp", 26 },
        { "血顶巨魔", 26 },
        { "Troll, Skullsplitter", 27 },
        { "劈颅巨魔", 27 },
        { "Prey", 28 },
        { "猎物", 28 },
        { "Beast - Wolf", 29 },
        { "狼人 2", 29 },
        { "Defias Brotherhood Traitor", 30 },
        { "叛变的迪菲亚盗贼(艾泽拉斯)", 30 },
        { "Friendly", 31 },
        { "友方", 31 },
        { "Trogg", 32 },
        { "穴居人", 32 },
        { "Troll, Frostmane", 33 },
        { "冰巨魔", 33 },
        { "Orc, Blackrock", 34 },
        { "黑石氏族兽人", 34 },
        { "Villian", 35 },
        { "Victim", 36 },
        { "牺牲品", 36 },
        { "Beast - Bear", 37 },
        { "熊", 37 },
        { "Ogre", 38 },
        { "食人魔", 38 },
        { "Kurzen's Mercenaries", 39 },
        { "库森的雇佣兵", 39 },
        { "Escortee", 40 },
        { "卫队", 40 },
        { "Venture Company", 41 },
        { "荆棘谷地精", 41 },
        { "Beast - Raptor", 42 },
        { "迅猛龙", 42 },
        { "Basilisk", 43 },
        { "石化蜥蜴", 43 },
        { "Dragonflight, Green", 44 },
        { "绿龙", 44 },
        { "Lost Ones", 45 },
        { "失落者", 45 },
        { "Blacksmithing - Armorsmithing", 46 },
        { "斯通纳德兽人", 46 },
        { "Ironforge", 47 },
        { "铁炉堡", 47 },
        { "Dark Iron Dwarves", 48 },
        { "黑铁矮人", 48 },
        { "Human, Night Watch", 49 },
        { "暮色森林守夜人", 49 },
        { "Dragonflight, Red", 50 },
        { "红龙", 50 },
        { "Gnoll - Mosshide", 51 },
        { "藓皮豺狼人", 51 },
        { "Orc, Dragonmaw", 52 },
        { "龙喉氏族兽人", 52 },
        { "Gnome - Leper", 53 },
        { "疯狂侏儒", 53 },
        { "Gnomeregan Exiles", 54 },
        { "诺莫瑞根流亡者", 54 },
        { "Leopard", 55 },
        { "豹", 55 },
        { "Scarlet Crusade", 56 },
        { "血色十字军", 56 },
        { "Gnoll - Rothide", 57 },
        { "烂皮豺狼人", 57 },
        { "Beast - Gorilla", 58 },
        { "猩猩", 58 },
        { "Thorium Brotherhood", 59 },
        { "瑟银兄弟会", 59 },
        { "Naga", 60 },
        { "纳迦", 60 },
        { "Dalaran", 61 },
        { "达拉然", 61 },
        { "Forlorn Spirit", 62 },
        { "弃灵", 62 },
        { "Darkhowl", 63 },
        { "Grell", 64 },
        { "劣魔", 64 },
        { "Furbolg", 65 },
        { "熊怪", 65 },
        { "Horde Generic", 66 },
        { "部落友军", 66 },
        { "Horde", 67 },
        { "部落", 67 },
        { "Undercity", 68 },
        { "幽暗城", 68 },
        { "Darnassus", 69 },
        { "达纳苏斯", 69 },
        { "Syndicate", 70 },
        { "辛迪加", 70 },
        { "Hillsbrad Militia", 71 },
        { "希尔斯布莱德民兵", 71 },
        { "Stormwind", 72 },
        { "暴风城", 72 },
        { "Demon", 73 },
        { "恶魔", 73 },
        { "Elemental", 74 },
        { "元素生物", 74 },
        { "Spirit", 75 },
        { "灵魂", 75 },
        { "Orgrimmar", 76 },
        { "奥格瑞玛", 76 },
        { "Treasure", 77 },
        { "宝物", 77 },
        { "Gnoll - Mudsnout", 78 },
        { "泥嘴豺狼人", 78 },
        { "HIllsbrad, Southshore Mayor", 79 },
        { "希尔斯布莱德，南海镇", 79 },
        { "Dragonflight, Black", 80 },
        { "黑龙", 80 },
        { "Thunder Bluff", 81 },
        { "雷霆崖", 81 },
        { "Troll, Witherbark", 82 },
        { "枯木巨魔", 82 },
        { "Leatherworking - Elemental", 83 },
        { "怪物 - 无组织", 83 },
        { "Quilboar, Razormane", 84 },
        { "钢鬃野猪人", 84 },
        { "Quilboar, Bristleback", 85 },
        { "刺背野猪人", 85 },
        { "Leatherworking - Dragonscale", 86 },
        { "怪物 - 有组织", 86 },
        { "Bloodsail Buccaneers", 87 },
        { "血帆海盗", 87 },
        { "Blackfathom", 88 },
        { "黑暗深渊", 88 },
        { "Makrura", 89 },
        { "龙虾人", 89 },
        { "Centaur, Kolkar", 90 },
        { "科卡尔半人马", 90 },
        { "Centaur, Galak", 91 },
        { "加拉克半人马", 91 },
        { "Gelkis Clan Centaur", 92 },
        { "吉尔吉斯半人马", 92 },
        { "Magram Clan Centaur", 93 },
        { "玛格拉姆半人马", 93 },
        { "Maraudine", 94 },
        { "玛洛迪", 94 },
        { "Theramore", 108 },
        { "塞拉摩", 108 },
        { "Quilboar, Razorfen", 109 },
        { "剃刀沼泽野猪人", 109 },
        { "Quilboar, Razormane 2", 110 },
        { "钢鬃野猪人 2", 110 },
        { "Quilboar, Deathshead", 111 },
        { "Enemy", 128 },
        { "敌人", 128 },
        { "Ambient", 148 },
        { "小动物", 148 },
        { "Nethergarde Caravan", 168 },
        { "奈瑟加德商队", 168 },
        { "Steamwheedle Cartel", 169 },
        { "热砂港", 169 },
        { "Alliance Generic", 189 },
        { "联盟", 189 },
        { "Nethergarde", 209 },
        { "守望堡", 209 },
        { "Wailing Caverns", 229 },
        { "哀嚎洞穴", 229 },
        { "Silithid", 249 },
        { "异种蝎", 249 },
        { "Silvermoon Remnant", 269 },
        { "银月幸存者", 269 },
        { "Zandalar Tribe", 270 },
        { "赞达拉部族", 270 },
        { "Blacksmithing - Weaponsmithing", 289 },
        { "黑水海盗", 289 },
        { "Scorpid", 309 },
        { "蝎子", 309 },
        { "Beast - Bat", 310 },
        { "蝙蝠", 310 },
        { "Titan", 311 },
        { "泰坦", 311 },
        { "Taskmaster Fizzule", 329 },
        { "工头费苏勒", 329 },
        { "Ravenholdt", 349 },
        { "拉文霍德", 349 },
        { "Gadgetzan", 369 },
        { "加基森", 369 },
        { "Gnomeregan Bug", 389 },
        { "Harpy", 409 },
        { "鹰身人", 409 },
        { "Burning Blade", 429 },
        { "火刃氏族", 429 },
        { "Shadowsilk Poacher", 449 },
        { "暗影蛛丝偷猎者", 449 },
        { "Searing Spider", 450 },
        { "Alliance", 469 },
        { "联盟 2", 469 },
        { "Ratchet", 470 },
        { "棘齿城", 470 },
        { "Wildhammer Clan", 471 },
        { "蛮锤部族", 471 },
        { "Goblin, Dark Iron Bar Patron", 489 },
        { "The League of Arathor", 509 },
        { "阿拉索联军", 509 },
        { "The Defilers", 510 },
        { "污染者", 510 },
        { "Giant", 511 },
        { "巨人", 511 },
        { "Argent Dawn", 529 },
        { "银色黎明", 529 },
        { "Darkspear Trolls", 530 },
        { "暗矛巨魔", 530 },
        { "Dragonflight, Bronze", 531 },
        { "青铜龙军团", 531 },
        { "Dragonflight, Blue", 532 },
        { "蓝龙军团", 532 },
        { "Leatherworking - Tribal", 549 },
        { "Engineering - Goblin", 550 },
        { "Engineering - Gnome", 551 },
        { "Blacksmithing - Hammersmithing", 569 },
        { "Blacksmithing - Axesmithing", 570 },
        { "Blacksmithing - Swordsmithing", 571 },
        { "Troll, Vilebranch", 572 },
        { "邪枝巨魔", 572 },
        { "Southsea Freebooters", 573 },
        { "南海海盗", 573 },
        { "Caer Darrow", 574 },
        { "凯尔达隆", 574 },
        { "Furbolg, Uncorrupted", 575 },
        { "未堕落的熊怪", 575 },
        { "Timbermaw Hold", 576 },
        { "木喉要塞", 576 },
        { "Everlook", 577 },
        { "永望镇", 577 },
        { "Wintersaber Trainers", 589 },
        { "冬刃豹训练师", 589 },
        { "Cenarion Circle", 609 },
        { "塞纳里奥议会", 609 },
        { "Shatterspear Trolls", 629 },
        { "断矛巨魔", 629 },
        { "Ravasaur Trainers", 630 },
        { "暴掠龙训练师", 630 },
        { "Majordomo Executus", 649 },
        { "管理者埃克索图斯", 649 },
        { "Beast - Carrion Bird", 669 },
        { "Beast - Cat", 670 },
        { "Beast - Crab", 671 },
        { "Beast - Crocilisk", 672 },
        { "Beast - Hyena", 673 },
        { "Beast - Owl", 674 },
        { "Beast - Scorpid", 675 },
        { "Beast - Tallstrider", 676 },
        { "Beast - Turtle", 677 },
        { "Beast - Wind Serpent", 678 },
        { "Training Dummy", 679 },
        { "Dragonflight, Black - Bait", 689 },
        { "Battleground Neutral", 709 },
        { "Frostwolf Clan", 729 },
        { "霜狼氏族", 729 },
        { "Stormpike Guard", 730 },
        { "雷矛卫队", 730 },
        { "Hydraxian Waterlords", 749 },
        { "海达希亚水元素", 749 },
        { "Sulfuron Firelords", 750 },
        { "萨弗隆火元素", 750 },
        { "Gizlock's Dummy", 769 },
        { "吉兹洛克的假人", 769 },
        { "Gizlock's Charm", 770 },
        { "Gizlock", 771 },
        { "吉兹洛克", 771 },
        { "Moro'gai", 789 },
        { "莫洛加", 789 },
        { "Spirit Guide - Alliance", 790 },
        { "Shen'dralar", 809 },
        { "辛德拉", 809 },
        { "Ogre (Captain Kromcrush)", 829 },
        { "Spirit Guide - Horde", 849 },
        { "Jaedenar", 869 },
        { "加德纳尔", 869 },
        { "Warsong Outriders", 889 },
        { "战歌氏族", 889 },
        { "Silverwing Sentinels", 890 },
        { "银翼要塞", 890 },
        { "Alliance Forces", 891 },
        { "联盟部队", 891 },
        { "Horde Forces", 892 },
        { "部落军队", 892 },
        { "Revantusk Trolls", 893 },
        { "恶齿巨魔", 893 },
        { "Darkmoon Faire", 909 },
        { "暗月马戏团", 909 },
        { "Brood of Nozdormu", 910 },
        { "诺兹多姆的子嗣", 910 },
        { "Silvermoon City", 911 },
        { "银月城", 911 },
        { "Might of Kalimdor", 912 },
        { "卡利姆多联军", 912 },
        { "PLAYER, Blood Elf", 914 },
        { "玩家，血精灵", 914 },
        { "Armies of C'Thun", 915 },
        { "克苏恩的军队", 915 },
        { "Silithid Attackers", 916 },
        { "异种虫类", 916 },
        { "The Ironforge Brigade", 917 },
        { "铁炉堡军团", 917 },
        { "RC Enemies", 918 },
        { "RC Objects", 919 },
        { "Red", 920 },
        { "红", 920 },
        { "Blue", 921 },
        { "蓝", 921 },
        { "Tranquillien", 922 },
        { "塔奎林", 922 },
        { "Farstriders", 923 },
        { "远行者", 923 },
        { "Sunstriders", 925 },
        { "逐日者", 925 },
        { "Magister's Guild", 926 },
        { "魔导师公会", 926 },
        { "PLAYER, Draenei", 927 },
        { "玩家，德莱尼", 927 },
        { "Scourge Invaders", 928 },
        { "天灾入侵者", 928 },
        { "Bloodmaul Clan", 929 },
        { "血槌氏族", 929 },
        { "Exodar", 930 },
        { "埃索达", 930 },
        { "Test Faction (not a real faction)", 931 },
        { "The Aldor", 932 },
        { "奥尔多", 932 },
        { "The Consortium", 933 },
        { "星界财团", 933 },
        { "The Scryers", 934 },
        { "占星者", 934 },
        { "The Sha'tar", 935 },
        { "沙塔尔", 935 },
        { "Shattrath City", 936 },
        { "沙塔斯城", 936 },
        { "Troll, Forest", 937 },
        { "森林巨魔", 937 },
        { "The Omenai", 938 },
        { "欧麦尼", 938 },
        { "The Sons of Lothar", 940 },
        { "洛萨之子 2", 940 },
        { "The Mag'har", 941 },
        { "玛格汉", 941 },
        { "Cenarion Expedition", 942 },
        { "塞纳里奥远征队", 942 },
        { "Fel Orc", 943 },
        { "邪兽人", 943 },
        { "Fel Orc Ghost", 944 },
        { "邪兽人幽灵", 944 },
        { "Sons of Lothar Ghosts", 945 },
        { "洛萨之子", 945 },
        { "Honor Hold", 946 },
        { "荣耀堡", 946 },
        { "Thrallmar", 947 },
        { "萨尔玛", 947 },
        { "Test Faction 2", 948 },
        { "Test Faction 1", 949 },
        { "ToWoW - Flag", 950 },
        { "ToWoW - Flag Trigger Alliance (DND)", 951 },
        { "Test Faction 3", 952 },
        { "Test Faction 4", 953 },
        { "ToWoW - Flag Trigger Horde (DND)", 954 },
        { "Broken", 955 },
        { "破碎者", 955 },
        { "Ethereum", 956 },
        { "复仇军", 956 },
        { "Earth Elemental", 957 },
        { "土元素", 957 },
        { "Fighting Robots", 958 },
        { "打架机器人", 958 },
        { "Actor Good", 959 },
        { "好演员", 959 },
        { "Actor Evil", 960 },
        { "坏演员", 960 },
        { "Stillpine Furbolg", 961 },
        { "止松熊怪", 961 },
        { "Crazed Owlkin", 962 },
        { "疯狂的枭兽", 962 },
        { "Chess Alliance", 963 },
        { "联盟棋子", 963 },
        { "Chess Horde", 964 },
        { "部落棋子", 964 },
        { "Monster Spar", 965 },
        { "Monster Spar Buddy", 966 },
        { "The Violet Eye", 967 },
        { "紫罗兰之眼", 967 },
        { "Sunhawks", 968 },
        { "炎鹰", 968 },
        { "Hand of Argus", 969 },
        { "阿古斯之手", 969 },
        { "Sporeggar", 970 },
        { "孢子村", 970 },
        { "Fungal Giant", 971 },
        { "真菌巨人", 971 },
        { "Spore Bat", 972 },
        { "孢子蝠", 972 },
        { "Monster, Predator", 973 },
        { "Monster, Prey", 974 },
        { "Void Anomaly", 975 },
        { "虚空畸能", 975 },
        { "Hyjal Defenders", 976 },
        { "海加尔防御者", 976 },
        { "Hyjal Invaders", 977 },
        { "海加尔入侵者", 977 },
        { "Kurenai", 978 },
        { "库雷尼", 978 },
        { "Earthen Ring", 979 },
        { "大地之环", 979 },
        { "The Burning Crusade", 980 },
        { "燃烧的远征", 980 },
        { "Arakkoa", 981 },
        { "鸦人", 981 },
        { "Zangarmarsh Banner (Alliance)", 982 },
        { "赞加沼泽军旗（联盟）", 982 },
        { "Zangarmarsh Banner (Horde)", 983 },
        { "赞加沼泽军旗（部落）", 983 },
        { "Zangarmarsh Banner (Neutral)", 984 },
        { "赞加沼泽军旗（中立）", 984 },
        { "Caverns of Time - Thrall", 985 },
        { "时光之穴 - 萨尔", 985 },
        { "Caverns of Time - Durnholde", 986 },
        { "时光之穴 - 敦霍尔德", 986 },
        { "Caverns of Time - Southshore Guards", 987 },
        { "时光之穴 - 南海镇卫兵", 987 },
        { "Shadow Council Covert", 988 },
        { "暗影议会", 988 },
        { "Keepers of Time", 989 },
        { "时光守护者", 989 },
        { "The Scale of the Sands", 990 },
        { "流沙之鳞", 990 },
        { "Dark Portal Defender, Alliance", 991 },
        { "Dark Portal Defender, Horde", 992 },
        { "Dark Portal Attacker, Legion", 993 },
        { "Inciter Trigger", 994 },
        { "Inciter Trigger 2", 995 },
        { "Inciter Trigger 3", 996 },
        { "Inciter Trigger 4", 997 },
        { "Inciter Trigger 5", 998 },
        { "Mana Creature", 999 },
        { "法力生物", 999 },
        { "Khadgar's Servant", 1000 },
        { "卡德加的仆从", 1000 },
        { "Bladespire Clan", 1001 },
        { "刀塔氏族", 1001 },
        { "Ethereum Sparbuddy", 1002 },
        { "复仇军 2", 1002 },
        { "Protectorate", 1003 },
        { "维序派", 1003 },
        { "Arcane Annihilator (DNR)", 1004 },
        { "Friendly, Hidden", 1005 },
        { "Kirin'Var - Dathric", 1006 },
        { "Kirin'Var - Belmara", 1007 },
        { "Kirin'Var - Luminrath", 1008 },
        { "Kirin'Var - Cohlien", 1009 },
        { "Servant of Illidan", 1010 },
        { "伊利丹的仆从", 1010 },
        { "Lower City", 1011 },
        { "贫民窟", 1011 },
        { "Ashtongue Deathsworn", 1012 },
        { "灰舌死誓者", 1012 },
        { "Spirits of Shadowmoon 1", 1013 },
        { "Spirits of Shadowmoon 2", 1014 },
        { "Netherwing", 1015 },
        { "灵翼之龙", 1015 },
        { "Wyrmcult", 1016 },
        { "拜龙教", 1016 },
        { "Treant", 1017 },
        { "树人", 1017 },
        { "Leotheras Demon I", 1018 },
        { "Leotheras Demon II", 1019 },
        { "Leotheras Demon III", 1020 },
        { "Leotheras Demon IV", 1021 },
        { "Leotheras Demon V", 1022 },
        { "Azaloth", 1023 },
        { "阿萨洛斯", 1023 },
        { "Rock Flayer", 1024 },
        { "剥石者", 1024 },
        { "Flayer Hunter", 1025 },
        { "剥石者猎手", 1025 },
        { "Shadowmoon Shade", 1026 },
        { "影月之魂", 1026 },
        { "Legion Communicator", 1027 },
        { "军团联络器", 1027 },
        { "Ravenswood Ancients", 1028 },
        { "乌鸦林古树", 1028 },
        { "Chess, Friendly to All Chess", 1029 },
        { "Black Temple Gates - Illidari", 1030 },
        { "Sha'tari Skyguard", 1031 },
        { "沙塔尔天空卫队", 1031 },
        { "Area 52", 1032 },
        { "52区", 1032 },
        { "Maiev", 1033 },
        { "玛维", 1033 },
        { "Skettis Shadowy Arakkoa", 1034 },
        { "斯克提斯阴影鸦人", 1034 },
        { "Skettis Arakkoa", 1035 },
        { "斯克提斯鸦人", 1035 },
        { "Dragonmaw Enemy", 1036 },
        { "龙喉之敌", 1036 },
        { "Alliance Vanguard", 1037 },
        { "联盟先遣军", 1037 },
        { "Ogri'la", 1038 },
        { "奥格瑞拉", 1038 },
        { "Ravager", 1039 },
        { "掠食者", 1039 },
        { "Frenzy", 1041 },
        { "狂鱼", 1041 },
        { "Skyguard Enemy", 1042 },
        { "天空卫队之敌", 1042 },
        { "Skunk, Petunia", 1043 },
        { "臭鼬", 1043 },
        { "Theramore Deserter", 1044 },
        { "塞拉摩叛逃者", 1044 },
        { "Northsea Pirates", 1046 },
        { "北海海盗", 1046 },
        { "Tuskarr", 1047 },
        { "海象人", 1047 },
        { "Troll, Amani", 1049 },
        { "阿曼尼巨魔", 1049 },
        { "Valiance Expedition", 1050 },
        { "无畏远征军", 1050 },
        { "Horde Expedition", 1052 },
        { "部落先遣军", 1052 },
        { "Westguard", 1053 },
        { "Spotted Gryphon", 1054 },
        { "Tamed Plaguehound", 1055 },
        { "Vrykul (Ancient Spirit 1)", 1056 },
        { "Vrykul (Ancient Siprit 2)", 1057 },
        { "Vrykul (Ancient Siprit 3)", 1058 },
        { "CTF - Flag - Alliance", 1059 },
        { "Test", 1060 },
        { "Vrykul Gladiator", 1062 },
        { "维库角斗士", 1062 },
        { "Valgarde Combatant", 1063 },
        { "The Taunka", 1064 },
        { "牦牛人", 1064 },
        { "Monster, Zone Force Reaction 1", 1065 },
        { "Monster, Zone Force Reaction 2", 1066 },
        { "The Hand of Vengeance", 1067 },
        { "复仇之手", 1067 },
        { "Explorers' League", 1068 },
        { "探险者协会", 1068 },
        { "Ram Racing Powerup DND", 1069 },
        { "Ram Racing Trap DND", 1070 },
        { "Craig's Squirrels", 1071 },
        { "The Kalu'ak", 1073 },
        { "卡鲁亚克", 1073 },
        { "Holiday - Water Barrel", 1074 },
        { "Holiday - Generic", 1075 },
        { "Iron Dwarves", 1076 },
        { "铁矮人", 1076 },
        { "Shattered Sun Offensive", 1077 },
        { "破碎残阳", 1077 },
        { "Fighting Vanity Pet", 1078 },
        { "战斗宠物", 1078 },
        { "Murloc, Winterfin", 1079 },
        { "冬鳞鱼人", 1079 },
        { "Friendly, Force Reaction", 1080 },
        { "Object, Force Reaction", 1081 },
        { "Vrykul, Sea", 1084 },
        { "Warsong Offensive", 1085 },
        { "战歌远征军", 1085 },
        { "Poacher", 1086 },
        { "Holiday Monster", 1087 },
        { "节日怪物", 1087 },
        { "Furbolg, Redfang", 1088 },
        { "Furbolg, Frostpaw", 1089 },
        { "Kirin Tor", 1090 },
        { "肯瑞托", 1090 },
        { "The Wyrmrest Accord", 1091 },
        { "龙眠联军", 1091 },
        { "Azjol-Nerub", 1092 },
        { "艾卓-尼鲁布", 1092 },
        { "The Silver Covenant", 1094 },
        { "银色盟约", 1094 },
        { "Grizzly Hills Trapper", 1095 },
        { "Wrath of the Lich King", 1097 },
        { "巫妖王之怒", 1097 },
        { "Knights of the Ebon Blade", 1098 },
        { "黑锋骑士团", 1098 },
        { "Wrathgate Scourge", 1099 },
        { "Wrathgate Alliance", 1100 },
        { "Wrathgate Horde", 1101 },
        { "CTF - Flag - Horde", 1102 },
        { "CTF - Flag - Neutral", 1103 },
        { "Frenzyheart Tribe", 1104 },
        { "狂心氏族", 1104 },
        { "The Oracles", 1105 },
        { "神谕者", 1105 },
        { "Argent Crusade", 1106 },
        { "银色北伐军", 1106 },
        { "Troll, Drakkari", 1107 },
        { "CoT Arthas", 1108 },
        { "CoT Stratholme Citizen", 1109 },
        { "CoT Scourge", 1110 },
        { "Freya", 1111 },
        { "弗蕾亚", 1111 },
        { "Mount - Taxi - Alliance", 1112 },
        { "Mount - Taxi - Horde", 1113 },
        { "Mount - Taxi - Neutral", 1114 },
        { "Elemental, Water", 1115 },
        { "Elemental, Air", 1116 },
        { "Sholazar Basin", 1117 },
        { "索拉查盆地", 1117 },
        { "Classic", 1118 },
        { "经典旧世", 1118 },
        { "The Sons of Hodir", 1119 },
        { "霍迪尔之子", 1119 },
        { "Iron Giants", 1120 },
        { "铁巨人", 1120 },
        { "Frost Vrykul", 1121 },
        { "冰霜维库人", 1121 },
        { "Earthen", 1122 },
        { "土灵", 1122 },
        { "Monster Referee", 1123 },
        { "The Sunreavers", 1124 },
        { "夺日者", 1124 },
        { "Hyldsmeet", 1125 },
        { "海德比武会", 1125 },
        { "The Frostborn", 1126 },
        { "霜脉矮人", 1126 },
        { "Orgrimmar (Alex Test)", 1127 },
        { "Tranquillien Conversion", 1136 },
        { "塔奎林声望转换", 1136 },
        { "Wintersaber Conversion", 1137 },
        { "霜刃豹声望转换", 1137 },
        { "Hates Everything", 1145 },
        { "憎世者", 1145 },
        { "Silver Covenant Conversion", 1154 },
        { "银色盟约声望转换", 1154 },
        { "Sunreavers Conversion", 1155 },
        { "夺日者声望转换", 1155 },
        { "The Ashen Verdict", 1156 },
        { "灰烬审判军", 1156 },
        { "CTF - Flag - Alliance 2", 1159 },
        { "CTF - Flag - Horde 2", 1160 },
    };
}

enum FactionStanding
{
    Hated = 1,
    Hostile = 2,
    Unfriendly = 3,
    Neutral = 4,
    Friendly = 5,
    Honored = 6,
    Revered = 7,
    Exalted = 8
}
